# permissions for end users to view electrictrees.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: electrictrees-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: etoperator
    app.kubernetes.io/part-of: etoperator
    app.kubernetes.io/managed-by: kustomize
  name: electrictrees-viewer-role
rules:
- apiGroups:
  - hiklas.com
  resources:
  - electrictrees
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hiklas.com
  resources:
  - electrictrees/status
  verbs:
  - get
